name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v6
    - name: Install pre-commit
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 10
        max_attempts: 3
        retry_on: error
        shell: bash
        on_retry_command: echo "::warning::Pre-commit installation failed, retrying..."
        command: |
          pip install pre-commit
    - name: Run pre-commit on changed files
      # Use the base and head SHAs from the pull request event context
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          pre-commit run \
             --from-ref "${{ github.event.pull_request.base.sha }}" \
             --to-ref   "${{ github.event.pull_request.head.sha }}" \
             --color=always
        else
        # push event
          pre-commit run \
             --from-ref "${{ github.event.before }}" \
             --to-ref   "${{ github.sha }}" \
             --color=always
        fi
